export const auctionMockData = {
  items: [
    {
      id: 18164,
      label: "Volkswagen Golf GTI BMT/Start-Stopp DE - LimS5 2.0 TSI BMT/Start-Stopp EU6, GTI, 2017 - 2018",
      endingTime: "2022-05-12T08:00:00.000Z",
      state: 2,
      minimumRequiredAsk: 1234,
      currentHighestBidValue: 0,
      numBids: 0,
      locationAddress: null,
      locationCity: "",
      locationZip: "20xxx",
      startedAt: "2022-05-10T14:53:04.964Z",
      createdAt: "2022-03-25T03:29:34.565Z",
      updatedAt: "2022-05-11T22:32:59.721Z",
      hotBid: true,
      originalMinimumRequiredAsk: null,
      allowInstantPurchase: true,
      instantPurchasePossibleUntil: "2022-05-11T15:00:04.964Z",
      advertisementHtmlContent: null,
      instantPurchasePrice: 13370,
      locationCountryCode: "DE",
      startingBidValue: 0,
      uuid: "80bf89a6-ea12-4281-8016-0309a284475e",
      _fk_uuid_vehicle: "e1fe4c36-afc7-4234-81d9-035d81763e8f",
      _fk_uuid_sellerUser: "4658acde-f4c2-47b9-ba1d-4f024087611e",
      _fk_uuid_highestBiddingBuyerUser: null,
      urlToPickupBuyerDocument: null,
      paymentProcess: 2,
      type: 1,
      _fk_uuid_creatingSellerUser: null,
      isTest: false,
      displayMinAsk: false,
      isLive: false,
      isTransportationDisabledManually: false,
      startingBidValueNet: 0,
      minimumRequiredAskNet: 0,
      originalMinimumRequiredAskNet: null,
      purchasePriceNet: 1234,
      currentHighestBidValueNet: 0,
      highestBidValueAtEndingTimeNet: null,
      instantPurchasePriceNet: 13370,
      lastOfferBySellerNet: null,
      previousLastOfferBySellerNet: null,
      counterOfferByBuyerNet: null,
      previousCounterOfferByBuyerNet: null,
      renegotiationMidpointValueNet: null,
      pickupInstructions: null,
      thirdPartyVATDepositTransferReference: null,
      thirdPartyVATDepositChargeReference: null,
      preventSellerFactoring: false,
      listingSurchargeFeeInvoiceReference: null,
      additionalTaxType: 0,
      additionalTaxValue: null,
      isVATReportable: false,
      thirdPartyAdditionalTaxRefundReference: null,
      uploadMethod: 4,
      amIInvolved: false,
      biddingAgentValue: 0,
      remainingTimeInSeconds: 29356,
      remainingTimeForInstantPurchaseInSeconds: null,
      associatedVehicle: {
        id: 18186,
        ez: "03/2022",
        make: "Volkswagen",
        mileageInKm: 123,
        model: "Golf GTI BMT/Start-Stopp [DE - LimS5 2.0 TSI BMT/Start-Stopp EU6, GTI, 2017 - 2018]",
        vin: "WVWZZZAUZHW383074",
        hadAccident: true,
        accidentDescription: "Damage repaired",
        category: 0,
        doors: 1,
        enginePowerInHp: 230,
        engineSizeInCcm: 1984,
        fuelType: 0,
        transmission: 1,
        upholstery: 2,
        ac: 2,
        coupling: 0,
        headlights: 3,
        navigation: 1,
        parkingAssistance: 3,
        sportPackage: 0,
        sunRoof: 1,
        vehicleHeater: 0,
        huReportExists: true,
        lastHu: null,
        numKeys: 1,
        numPreOwners: 3,
        vatIdReportable: false,
        urlToAttachment1: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1648178977/ib3ezs6q8chr16j4jq7u.pdf",
        urlToAttachment2: null,
        urlToAttachment3: null,
        additionalDamages: "Deficiencies",
        urlToVehicleSummarySheet: null,
        euroNorm: "Euro 6",
        dimensionWidthInCm: 1799,
        dimensionHeightInCm: 1492,
        dimensionLengthInCm: 4258,
        unloadedWeightInKg: 1386,
        numSeats: 5,
        isReimportedVehicle: true,
        datBaseModelRaw: "Golf VII Lim. (BQ1/BE2)(01.2017->)",
        uuid: "e1fe4c36-afc7-4234-81d9-035d81763e8f",
        origin: 3,
        dataSource: 1,
        createdAt: "2022-03-25T03:29:31.716Z",
        updatedAt: "2022-05-11T22:32:59.731Z",
        deletedAt: null,
        lastServiceInspectionDate: null,
        lastServiceInspectionMileage: null,
        isCocDocumentAvailable: null,
        countryOfLastRegistration: "DE",
        bodyColorCode: 7,
        readyToDrive: 0,
        readyToDriveDetails: null,
        hasDamages: true,
        damagesDescription: "Existing accidetn damage",
        additionalInfo: "Additional information",
        dataWarnings: [],
        serviceHistoryAvailability: 1,
        fullServiceHistoryType: 0,
        hasMaintenanceBook: null,
        fieldsConfirmationStatus: {
          ac: {
            value: null,
            confirmed: null,
            initValue: 2,
          },
          sunRoof: {
            value: null,
            confirmed: null,
            initValue: 1,
          },
          category: {
            value: null,
            confirmed: null,
            initValue: 0,
          },
          coupling: {
            value: null,
            confirmed: null,
            initValue: 0,
          },
          euroNorm: {
            value: null,
            confirmed: null,
            initValue: "Euro 6",
          },
          numSeats: {
            value: null,
            confirmed: null,
            initValue: 5,
          },
          headlights: {
            value: null,
            confirmed: null,
            initValue: 3,
          },
          navigation: {
            value: null,
            confirmed: null,
            initValue: 1,
          },
          sportPackage: {
            value: null,
            confirmed: null,
            initValue: 0,
          },
          vehicleHeater: {
            value: null,
            confirmed: null,
            initValue: 0,
          },
          parkingAssistance: {
            value: null,
            confirmed: null,
            initValue: 3,
          },
        },
        licensePlate: null,
        urlToMotorSound: "https://res.cloudinary.com/castle-tech-gmbh-dev/video/upload/v1652287207/i2wprsurkhmvfkj3dtp3.mp4",
        fuelConsumption: {},
        co2Emission: {},
        urlsByLanguageToExpose: {
          en: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1652305911/iz2e5bxryizqzl302g5z.pdf",
          nl: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1652306114/sasa9dwbittdng199uef.pdf",
          pl: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1652306095/tlkc3gotkzqdq90p4pys.pdf",
          sk: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1652305941/lcsphnbydfcdpuydduia.pdf",
        },
        commercialUsage: [1],
        attachments: [],
        damages: [],
        equipmentData: [],
        equipmentHighlights: [],
        vehicleImages: [
          {
            url: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1648178972/theejxitadkdf1isi9ev.jpg",
            perspective: 0,
          },
        ],
        tires: [],
        paintState: [],
        technicalState: [],
      },
      amIHighestBidder: false,
      sellerContact: null,
      rating: null,
      isTransportationAllowedForRegion: true,
      isExternalPaymentAllowed: true,
      remainingDaysUntilReauctioning: null,
      remainingDaysUntilLatePickup: null,
      latePickupFee: null,
      isTransportationBookingPossible: true,
      isExpressPickupAvailable: false,
      pickupPossibleInDays: null,
      sellerAccount: {
        shouldApplyStandingCosts: true,
      },
      amIRegularBuyer: false,
      isCrossBorderNetSale: false,
      distanceToVehicleInKms: 0,
      buyerPurchaseFee: 79,
      buyerSuccessFee: 99,
      vatAmount: 0,
      vatRate: 0,
      isMinAskReached: false,
      transportationTask: null,
      sellerType: 0,
      enforceTransportation: false,
      isTransportationAvailable: true,
    },
  ],
  page: 1,
  total: 50,
};
